generation:
  seed: 0xb6b5db5d5ad5f51a
  terrain:
    layers:
      - block_id: 0
        height_base: 40.0
        height_noise:
          frequency: 0.03
          amplitude: 20.0
          lacunarity: 2.0
          persistence: 0.5
          octaves: 4
      - block_id: 1
        height_base: 5.0
        height_noise:
          frequency: 0.01
          amplitude: 2.0
          lacunarity: 2.0
          persistence: 0.5
          octaves: 2
  caves:
    max_per_chunk: 2
    max_segment: 10
    step: 5.0
    min_height: 10.0
    max_height: 30.0
    dig_noise:
      frequency: 0.1
      amplitude: 1.0
      lacunarity: 2.0
      persistence: 0.5
      octaves: 4
    radius_base: 2.0
    radius_noise:
      frequency: 0.1
      amplitude: 3.0
      lacunarity: 2.0
      persistence: 0.5
      octaves: 1
