- textures:
  - "stone.png"
  - "stone.png"
  - "stone.png"
  - "stone.png"
  - "stone.png"
  - "stone.png"
- textures:
  - "grass_side.png"
  - "grass_side.png"
  - "grass_side.png"
  - "grass_side.png"
  - "grass_bottom.png"
  - "grass_top.png"
